apiVersion: v1alpha1
group: management
scope: griffinrecords
kind: Stage
title: API Development
name: api-development
tags: ["axway", "edge", "v7", "api-development"]
spec:
    dataplane: axway-edge
    description: Stage for API Development org.
    policies:
        writersauth: axway-tokenauth
        readersauth: axway-tokenauth
    organizationName: API Development
