# Not sure if this is a good idea or not...for now a stage per org id
apiVersion: v1alpha1
group: management
scope: axway-edge
kind: Stage
title: API Development
name: api-development
tags: ["axway", "edge", "v7", "api-development"]
spec:
    description: Stage for API Development org.
    policies:
        writersauth: axway-tokenauth
        readersauth: axway-tokenauth
    organizationId: c2c95205-1dd3-4cc4-8507-6e23d4700a47
