apiVersion: v1alpha1
group: management
scope: griffinrecords
kind: PathRoute
title: Route for Musical Instruments v1
name: secgriffininstrumentsv1route
spec:
    virtualAPIDefinition: secgriffininstrumentsv1
    prefix: /api/music
    target:
        apiServiceInstance: musicalinstrumentsv1ars
