apiVersion: v1alpha1
group: management
scope: griffinrecords
kind: AuthRule
title: AuthRule for Griffin Instruments v1
name: griffininstrumentsv1writers
spec:
    virtualAPIDefinition: griffininstrumentsv1
    jwt:
        policy: writersauth
---
apiVersion: v1alpha1
group: management
scope: griffinrecords
kind: AuthRule
title: AuthRule for Griffin Instruments v1
name: griffininstrumentsv1readers
spec:
    virtualAPIDefinition: griffininstrumentsv1
    jwt:
        policy: readersauth
