apiVersion: v1alpha1
group: management
scope: griffinrecords
kind: CorsRule
title: CORS Rule on Griffin Instruments V1 with Auth
name: griffininstrumentsv1cors
spec:
    description: Cross-Origin Resource Sharing rule for the Griffin Instruments Virtual API.
    virtualAPIDefinition: griffininstrumentsv1
    accessControlAllowOrigin: "*"
    accessControlMaxAge: 600
    accessControlAllowHeaders:
        - Location
        - X-Axway-Tenant-Id
    accessControlAllowMethods:
        - GET
        - PUT
        - POST
        - DELETE
